// Mocks generated by Mockito 5.4.6 from annotations
// in dzevent/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dzevent/data/databases/db_association.dart' as _i4;
import 'package:dzevent/data/databases/db_auth.dart' as _i7;
import 'package:dzevent/data/models/assoc_model.dart' as _i2;
import 'package:dzevent/data/models/user_model.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAssociationModel_0 extends _i1.SmartFake
    implements _i2.AssociationModel {
  _FakeAssociationModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AssociationTable].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssociationTable extends _i1.Mock implements _i4.AssociationTable {
  MockAssociationTable() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get db_table =>
      (super.noSuchMethod(
            Invocation.getter(#db_table),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#db_table),
            ),
          )
          as String);

  @override
  set db_table(String? value) => super.noSuchMethod(
    Invocation.setter(#db_table, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool> insertRecord(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#insertRecord, [data]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> deleteRecord(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecord, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getRecordbyId(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRecordbyId, [id]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getAllRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRecords, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<Map<String, dynamic>?> getRecord({
    required String? where,
    required List<Object>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecord, [], {
              #where: where,
              #whereArgs: whereArgs,
            }),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<List<Map<String, dynamic>>?> getRecords({
    required String? where,
    required List<Object>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecords, [], {
              #where: where,
              #whereArgs: whereArgs,
            }),
            returnValue: _i6.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i6.Future<List<Map<String, dynamic>>?>);

  @override
  _i6.Future<bool> deleteRecords() =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecords, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> updateRecord(Map<String, dynamic>? data, String? id) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecord, [data, id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> updateUser(Map<String, dynamic>? data, int? id) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [data, id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<_i2.AssociationModel>> getAssociationUnv() =>
      (super.noSuchMethod(
            Invocation.method(#getAssociationUnv, []),
            returnValue: _i6.Future<List<_i2.AssociationModel>>.value(
              <_i2.AssociationModel>[],
            ),
          )
          as _i6.Future<List<_i2.AssociationModel>>);

  @override
  _i6.Future<List<_i2.AssociationModel>> getAssociation(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAssociation, [id]),
            returnValue: _i6.Future<List<_i2.AssociationModel>>.value(
              <_i2.AssociationModel>[],
            ),
          )
          as _i6.Future<List<_i2.AssociationModel>>);

  @override
  _i6.Future<bool> verifyAssociation(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#verifyAssociation, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> deleteAssociation(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAssociation, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [DBAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockDBAuth extends _i1.Mock implements _i7.DBAuth {
  MockDBAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.AssociationModel> getAssociationByCredentials(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAssociationByCredentials, [email, password]),
            returnValue: _i6.Future<_i2.AssociationModel>.value(
              _FakeAssociationModel_0(
                this,
                Invocation.method(#getAssociationByCredentials, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i6.Future<_i2.AssociationModel>);

  @override
  _i6.Future<List<_i2.AssociationModel>> getAssociationUnv() =>
      (super.noSuchMethod(
            Invocation.method(#getAssociationUnv, []),
            returnValue: _i6.Future<List<_i2.AssociationModel>>.value(
              <_i2.AssociationModel>[],
            ),
          )
          as _i6.Future<List<_i2.AssociationModel>>);

  @override
  _i6.Future<_i3.UserModel> getUserByCredentials(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByCredentials, [email, password]),
            returnValue: _i6.Future<_i3.UserModel>.value(
              _FakeUserModel_1(
                this,
                Invocation.method(#getUserByCredentials, [email, password]),
              ),
            ),
          )
          as _i6.Future<_i3.UserModel>);

  @override
  _i6.Future<bool> checkUnique(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#checkUnique, [email]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i3.UserModel> getUserById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [id]),
            returnValue: _i6.Future<_i3.UserModel>.value(
              _FakeUserModel_1(this, Invocation.method(#getUserById, [id])),
            ),
          )
          as _i6.Future<_i3.UserModel>);
}
