// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Aag7KsybUnaByJlbo5WqcwA6iC_E8bs',
    appId: '1:104980659662:web:1e1530bfd9b67ed087bf9f',
    messagingSenderId: '104980659662',
    projectId: 'dzevent-notifications',
    authDomain: 'dzevent-notifications.firebaseapp.com',
    storageBucket: 'dzevent-notifications.firebasestorage.app',
    measurementId: 'G-220M3011YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAPIyZ74BgpF2hUgaj_tUYqOCivKkTEhs',
    appId: '1:104980659662:android:feaaa91e11eb07a687bf9f',
    messagingSenderId: '104980659662',
    projectId: 'dzevent-notifications',
    storageBucket: 'dzevent-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0crmgLATX9qH6I7O5uxYFroSviEQhs7w',
    appId: '1:104980659662:ios:3840f6b18bf1015587bf9f',
    messagingSenderId: '104980659662',
    projectId: 'dzevent-notifications',
    storageBucket: 'dzevent-notifications.firebasestorage.app',
    iosBundleId: 'com.example.dzevent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0crmgLATX9qH6I7O5uxYFroSviEQhs7w',
    appId: '1:104980659662:ios:3840f6b18bf1015587bf9f',
    messagingSenderId: '104980659662',
    projectId: 'dzevent-notifications',
    storageBucket: 'dzevent-notifications.firebasestorage.app',
    iosBundleId: 'com.example.dzevent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Aag7KsybUnaByJlbo5WqcwA6iC_E8bs',
    appId: '1:104980659662:web:4587bffe4cc1ca7687bf9f',
    messagingSenderId: '104980659662',
    projectId: 'dzevent-notifications',
    authDomain: 'dzevent-notifications.firebaseapp.com',
    storageBucket: 'dzevent-notifications.firebasestorage.app',
    measurementId: 'G-P2SCH5WGCF',
  );
}
